#cloud-config
chpasswd:
  list: |
    root:str3ams3ts
  expire: false
runcmd:
  - echo "root soft nofile 40000" >> /etc/security/limits.conf && echo "root hard nofile 64000" >> /etc/security/limits.conf
  - echo "session required pam_limits.so" >> /etc/pam.d/common-session
  - cd /root
  - sudo apt-get -y install git
  - git clone https://github.com/kiritbasu/training.git
  - cd training
  - chmod 744 *.sh
  - ./ubuntu-bootstrap.sh
  - sleep 10
  - ./cloudera-bootstrap.sh
  - sleep 10
  #copy Hive config files
  - ./copy_hive_conf.sh
final_message: "The system is finally up, after $UPTIME seconds"
